name: Terraform Prod

on:
  #workflow_dispatch:
  push:
    branches:
      - main
    #paths:
      #- "terraform/**" this is commented out because paths works if their is any changes made in the terraform folder, but we want to trigger the workflow when there is a push to prod branch, regardless of the changes made in the terraform folder.

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment: production

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform fmt -check -recursive
      - name: Create prod.tfvars
        run: |
          cp environments/prod/prod.tfvars.example environments/prod/prod.tfvars
          sed -i 's|replace_with_secret|${{ secrets.TF_VAR_db_password }}|' environments/prod/prod.tfvars
      - run: terraform validate
      - run: terraform plan -var-file=environments/prod/prod.tfvars
      #- run: terraform apply -auto-approve -var-file=environments/prod/prod.tfvars