name: Terraform Staging

on:
  push:
    branches:
      - staging
    #paths:
      #- "terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform fmt -check -recursive
      - name: Create staging.tfvars
        run: |
          cp environments/staging/staging.tfvars.example environments/staging/staging.tfvars
          sed -i 's|replace_with_secret|${{ secrets.TF_VAR_db_password }}|' environments/staging/staging.tfvars  
      - run: terraform validate
      - run: terraform plan -var-file=environments/staging/staging.tfvars
      #- run: terraform apply -auto-approve -var-file=environments/staging/staging.tfvars